# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build keebio/iris/rev8'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["keebio/iris/rev8"]'
